### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by j4ckieee** [MiguelFndz/CS361-Unit-Conversion-Microservice#1]
Converting *to* oz is not working

**Comment by j4ckieee** [comment]
Please also include g, kg, mL, and L (I turned down the option to include this earlier, but now realize I need it)

**Comment by MiguelFndz** [comment]
Added conversions between metric units, not sure what was wrong with converting to oz, can you elaborate on what was wrong? It seemed to work fine for me
